import type { Metadata } from "next";
import "./globals.css";
import { Header1 } from "./components/NavBar/NavBar";
import { Oxanium, Outfit } from "next/font/google";

const oxanium = Oxanium({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"], // ← agregá "800"
  variable: "--font-oxanium",
});
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
  variable: "--font-outfit", // ← nombre distinto
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${oxanium.variable} font-outfit antialiased`}
      >
        <Header1 />
        {children}
      </body>
    </html>
  );
}
